apiVersion: v1
kind: Pod
metadata:
  name: database
spec:
  containers:
    - name: database-container
      image: mysql:5.7
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: "loja"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"